### ISSUE TITLE
User Guide / Error Running Program / Enhancements

### ISSUE THREAD

**Issue by cavalia88** [boranblok/nntpPoster#10]
Hi,

I have not been successful in running your program on Windows 10. Despite setting up the settings.config file, I have not been able to run the nntpposter.exe. Always seem to get error messages (appended below).

(i) Is there a user guide on how to use your program? 
(ii) Must it be installed in a particular location? 
(iii) How do you know if the settings.config file has been setup correctly? Is there any other *.config file that needs to be amended?
(iv) As I usually prepare the rar and par files with my own script, how do I disable to rar/par functions in your program? (i.e. I just want to use your software purely for posting purposes)

Error message:

Unhandled Exception: System.Runtime.Serialization.SerializationException: Error in line 1 position 169. 'Element' 'SearchUrl' from namespace 'Util.Configuration' is not expected. Expecting element 'ParLocation | PostFailedFolder | RarLocation | RarNParSettings'. at System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(XmlReaderDelegator xmlReader, Int32 memberIndex, Int32 requiredIndex, XmlDictionaryString[] memberNames) at System.Runtime.Serialization.XmlObjectSerializerReadContext.GetMemberIndexWithRequiredMembers(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, XmlDictionaryString[] memberNamespaces, Int32 memberIndex, Int32 requiredIndex, ExtensionDataObject extensionData) at ReadSettingsFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] ) at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context) at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader) at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract) at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns) at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver) at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver) at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader) at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream) at Util.Configuration.Settings.LoadSettings(String fileName) in c:\Users\Ben\Documents\Visual Studio 2013\Projects\NewsPoster\nntpPoster\Util\Configuration\Settings.cs:line 35 at nntpPoster.Program.Main(String[] args) in c:\Users\Ben\Documents\Visual Studio 2013\Projects\NewsPoster\nntpPoster\nntpPoster\Program.cs:line 46

(v) Why does you software always reference your own native folders (e.g. c:\Users\Ben\Documents\Visual Studio 2013)?
(vi) Logging function does not seem to have been enabled for nntpposter.exe

**Comment by boranblok** [comment]
(i) the readme.md the settings.config also has inline documentation near every parameter.
(ii) no peticular location required.
(iii) you check the error logs. Something is wrong in the settings.config with the searchUrl tag, have you used more than one? (I have seen that before)
(iv) I would recommend the bare nntpPoster.exe for that you supply a file or folder to that. However I think it also rars and pars. If you want to do that yourself you'll have to fork the code and modify it.
(v) theseare the debug stacktraces and refer to the original source code location.
(vi) I will look into that. But the nntpPoster has significantly less use of the settings since it is not as automated. So some mistakes in settings might be skipped altogether there.

**Comment by cavalia88** [comment]
/Thanks for responding despite the festive seasons.
(i) I'm a total newbie with no programming experience. No idea how to use the SearchURL setting. What should I change in the initial setting? Possible to provide an example?
(ii) No programming background at all. No idea how to amend code and create new fork. I'm guessing basically one needs to create a switch to enable/disable rar and par functions? Any possibility this enhancement can be introduced sometime soon?
(iii) If random password parameter is set to true, how does a user know which random password was assigned to a particular upload? How does user than unrar the files without know what the random password was?

**Comment by boranblok** [comment]
(i) I cant help you very much there unless you can send me your config so I can look at it. However, removal of strict ordering of the parameters is on my todo list.
It wont matter much for the nntpPoster that much either.
(ii) The nntpPoster will work,the nntpAutoPoster will not since it obfuscates and needs verification stuff gets indexed ok.
(iii) I will look into adding this as a parameter, but is there any reason you want to rar and par yourself? Right now the message size is taken into account for instance so rar files and par files get made that fit nicely into a number of usenet messages so no space gets wasted.
(iv) The random password is put into the nzb <meta type="password"> tag. Clients like nzbGet and sabNzb can handle this tag and automatically apply this password to the downloaded rars.
(v) I think disabling rarring and parring myself will make this possible. I'll look into it. For the nntpPoster this should be rather easy since I started out with it not rarring and parring. (will have to look at the code again)

**Comment by cavalia88** [comment]
(I) Please see my settings.config file ( https://drive.google.com/file/d/0B696193P842Fb3FGMEZSdTY0dVE/view?usp=sharing ). 
(ii) It seems that nntpposter.exe will not work if searchURL parameter is not set (even though it is not required). this is based on your analysis of the error messages I get
(iii) Few reasons (a) using multipar which use GPU to aid in par creation, 3 times faster (b) able to set random password for rar based on my own dos script (password at least >45 alphanumeric) (c) able to choose and set where rar and par files are created (i.e. source file is on HDD whilst rar/par files created on SSD - speeds up process)
(iv) not familiar with metatags. The metatag will automatically be inserted into the NZB that is generated? I usually manually add password to the end of the NZB file name (e.g. abc {{password}} ) and it gets picked up in SABNZB
(v) Really appreciate your assistance in getting the basic nntpposter.exe to work. Hope to hear from you on this soon. Wishing you a Merry Christmas !!

**Comment by cavalia88** [comment]
Any luck figuring out what is wrong with my settings.config file? Or is it more of a coding issue with the nntpposter.exe that will require some time to rectify?

**Comment by boranblok** [comment]
sorry, holidays, not much time atm.

**Comment by cavalia88** [comment]
No worries. Please have a look at it when you can find the time. Happy holidays

**Comment by cavalia88** [comment]
What's new in version 0.7? is the standalone nntpPoster working now?

**Comment by boranblok** [comment]
No, this was adding priority queueing to the auto poster.

The standalon nntpPoster works, but you wanted a version thad did not rar and par, this has not yet been added.

**Comment by boranblok** [comment]
closing issue, no rarring and parring is outside of the scope of the project. Forking is recommended.
