### ISSUE TITLE
attach an .nfo?

### ISSUE THREAD

**Issue by judhat2** [boranblok/nntpPoster#17]
How do I attach an .nfo file to an upload?  I have tried putting the .mkv and .nfo in the "watch" folder, and I have tried putting the .mkv and .nfo inside a separate folder inside the "watch" folder.  It seems that nntpPoster just ignores the .nfo.

**Comment by boranblok** [comment]
I will have to test this myself, but normally if you place multiple files into a folder inside the watch location it picks them all up into one release. can you check during processing if the generated rar files contain the .nfo ?

**Comment by judhat2** [comment]
I put the .nfo in with the other file in a subdirectory and, you're right, both were included in the rar files.  However, the indexers couldn't find the .nfo file and attach it to the nzb details page.  I think the .nfo has to be included like this `7re6i65wri446d8646hwq6dq76r2yr [001/169] "7re6i65wri446d8646hwq6dq76r2yr.nfo" yEnc (1/1)` for the nzb indexer to see it and include it in the nzb details page.  Can the code be changed to allow this type of posting?

Also, while doing the test post using a subdirectory in a watch directory, I think I noticed a bug.  The rar/par file names were obfuscated, but the actual files inside the rar did not have obfuscated names.  When I don't use subdirectories, then both the rar/par files and the files inside them have obfuscated names.

**Comment by judhat2** [comment]
On second thought, it might not be a good idea to attach an .nfo like that. I imagine that could allow the obfuscated post to be identified quite easily by anyone.

**Comment by boranblok** [comment]
First of all, obfuscation as it is done now can only be applied to a single file. Since the deobfuscation part can only pass one piece of information. (the original filename) this is impossible if there are multiple original files.

So it is by design that multiple files are not obfuscated, it is currently not technically possible in the way obfuscation is handled. Other ways might be possible. But for now only the nzb name itself is used as this info.

If you want to increase lifespan you could in theory use passwords. The nzbs that are output in that case have the password meta tag which is supported transparently by nzbget and sabnzbd at least. (the end user never gets asked for a password, the one supplied in the nzb file is used automatically) You do need to enable nzb file output however, or have the nzbs sent somewhere with the api though.

**Comment by judhat2** [comment]
Ok, good to know about the limit of one file for obfuscation.  

I tried using the random password option, but the indexer didn't pick it up.  Well, it did momentarily in the pre-index releases. But I guess it saw that it was passworded and removed it from the indexer.

**Comment by boranblok** [comment]
Yes, the indexer needs to support passworded nzbs itself, not many indexes will keep these around.
