### ISSUE TITLE
Initial indexer notification not notifying

### ISSUE THREAD

**Issue by stephenl03** [boranblok/nntpPoster#31]
After the upload's name is cleaned, the logs indicate that nntpPoster is making a request to the `ObfuscatedNotificationUrl` but no call is ever made when `NotificationType=NzbPost` [1]. When `NotificationType=NewznabHash` it uses the `ObfuscatedNotificationUrl` and configured parameters to make a request. 

[1]
```
2017-10-10 05:58:15,576 INFO 6 nntpAutoposter.AutoPoster - Cleaned the name [REDACTED.2016.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSi
LON] to [REDACTED.2016.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON]
2017-10-10 06:02:02,121 INFO 7 nntpAutoposter.IndexerNotifierBase - Notified indexer that obfuscated release [REDACTED-UUID] is actually [REDACTED.2016.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON]
2017-10-10 06:16:39,557 DEBUG 6 ExternalProcessWrappers.ExternalProcessWrapperBase - Executing process: [/usr/bin/rar a -ep1  -m0 -r -v104960000b
  "/opt/nntpPoster/working/REDACTED-UUID_readyToPost/REDACTED-UUID"
```

**Comment by boranblok** [comment]
And how do you come to that conclusion?

The two notifiers work differently, the newznabhash sends a get request indicating hash and original name. This can be done before the posting is even completed. The nzbPost method however sends an nzb file to an http form (so it is a POST operation) and has to wait till the entire nzb has been created, (so all parts are uploaded)

By design the second method will send notifications later than the first method.

Granted the nzbPost is a rather index specific method of notification. (which index shall not be named)

**Comment by stephenl03** [comment]
So with either method, two log entries are generated. One at the beginning of the process and another once the upload is completed. If using the newznabhash method, two calls actually happen. If using the nzbpost method, only one call is done when uploading is complete. I was just wanting to ensure I wasn’t missing something.
