### ISSUE TITLE
Posts are not indexed by search engines

### ISSUE THREAD

**Issue by manzing** [boranblok/nntpPoster#42]
Hi,
The title says it all, i set "UseObfuscation=yes" setting, search engines like Binsearch and NZBKing do not show posts in search results. Only NZBindex can find them.
Issue is still present without obfuscation.
Maybe this is due to non-standard headers ?

I can't find any solution to make it work using ini configuration.
Any help ?
Thanks

**Comment by boranblok** [comment]
Obfuscation is intended to obfuscate posts from open search engines like that. So that is the whole point.

Also, not every index indexes every category, it might be that you are posting to a subcategory that NZBIndex indexes, but the other two dont.

Can you enable nzb output and see if you can download using the generated nzb? This is at least a basic verification your files get to and from usenet.

**Comment by manzing** [comment]
I use groups that are indexed by all 3 search engines i mentionned. In fact, if i use binsearch "browse newsgroup" feature i can see the post, but direct search shows no results. The problem is only direct search is suitable for long term access (or nzb but i can lose the file).
I already enabled nzb output and download is fine using nzb.
This is not a big deal, but i can see other obfuscated posts (not mine) that can be retrieved using basic search, so i was wondering why some posts are correctly indexed and some are not despite in appearance they look similar (obfuscated, similar name length...) and if there was something i can do tho fix this.
That said, this is a nice piece of software and the automation of rar / par / posting using ssl process is greatly enjoyable!

**Comment by boranblok** [comment]
Just so I understand the problem a bit more.

You are posting an obfuscated post. so that becomes a GUID.

Then you search for that GUID and you cannot find them ?

What exactly is the end goal then exactly? If you dont store the nzbs or dont notify an indexer which guid is what real file you cannot really find them again.

Or are you uploading without obfuscation? If that no longer works I probably introduced a bug recently and I'd have to look into that. If this is the case can you upload a small (+- 5 MB) test file and share the nzb?

**Comment by manzing** [comment]
Yes, it is exactly the issue. 
Without obfuscation posts are found using search engines (sorry for my mistake in first post) so i think you don't have to worry about a recently introduced bug.
The end goal is to be able to find a post even if the nzb is lost or unavailable, just using the GUID.
As i said before, it works with NZBindex, but not with Binsearch.
I tried with disabled obfuscation, and manually set scrambled names. Binsearch display a search result for a post with a 27 characters name, but not one with 32 caracters. I guess this is specific to binsearch, as the limit seems to be around 30 characters.
A workaround could be the ability to set the GUID's length within nntpposter using ini files, but as it is not really useful i would understand you don't want to implement this feature.
Thanks again for your answer.

**Comment by boranblok** [comment]
Well a guid with 27 characters is no longer a guid unless I use a different encoding (a guid can be encoded with something other than base16 (hex))

Do you use the `SpreadFilesOverTargetNewsgroups` setting? As this probably makes general indexers ignore a post as well.

If it is due to the length I could look into other GUID encoding schemes for the subject, this is not that much of an effort I'd think.

**Comment by manzing** [comment]
No i didn't use `SpreadFilesOverTargetNewsgroups `  setting as i don't really understand what is its purpose.
I think this is definitly due to length but it obviously affect Binsearch only, so you don't need to spend your time on this unless it is really not time consuming.
I suppose you have more important things on your todo list (like multiple usenet providers or so).

Another issue a friend faced is that when using several groups, he cannot post articles. here is the error we see in log :
System.Exception: Article failed to post: 441 Invalid group a.b.multimedia a.b.test
We double checked his watch.ini together and it is set like mine, but i have no issue. I sent him my file and he still has same issue.
Another friend have no issue too. We think this is due to the usenet provider (we don't have the same) but if you have any lead to help him use several groups it would be great.
Thanks a lot.

**Comment by boranblok** [comment]
does he use the pipe characer |  in between groups in the config? It seems to me like he configured it with a space and I am posting to "a.b.multimedia a.b.test" which would indeed not be a valid usenet group.

The `SpreadFilesOverTargetNewsgroups` option by the way spreads usenet file parts over different groups.

So if a file gets split in 5 message parts and you have a.b.c|d.e.f configured as groups it will post part 1,3,5 to a.b.c and parts 2,4 to d.e.f

No single group contains the entire file this way.

This is a bit of an advanced obfuscation technique and is skirting the limits of the nzb format a bit.

But it works in all clients I tested on so far.

**Comment by manzing** [comment]
Ok thanks for the explanation :) 
Yes, he uses a pipe for sure (i checked his file and picked the line : TargetNewsgroups=a.b.multimedia|a.b.test), that's why we cannot understand. 
My watch.ini works flawlessly at home, and when i give it to him, he uses it as is and upload does not work... This is really weird.

**Comment by manzing** [comment]
Hi
Just want to let you know that the issue about posting to several groups was actually due to the usenet provider. My friend tested same watch.ini file with another provider and he does not have any problem anymore.
The faulty provider is usenet.farm. It could help you if you have similar reports.

**Comment by boranblok** [comment]
Thanks you for this feedback. This can be used to help others in the future.
