### ISSUE TITLE
Use parpar for par file creation

### ISSUE THREAD

**Issue by mzarglis** [boranblok/nntpPoster#49]
Would it be possible it use parpar to create pars?

**Comment by boranblok** [comment]
This was added a few releases back.

check out the [nodejsParPar.ini](https://github.com/boranblok/nntpPoster/blob/master/Util/conf/99_nodejsParPar.ini) sample config file, you have to modify and copy this to the userconf folder in order to use this.

Be aware issues have been reported with some par2 files not being up to spec, this is why nodejsParPar is not the default par generator.
