### ISSUE TITLE
Verify Upload

### ISSUE THREAD

**Issue by jonnyboy** [boranblok/nntpPoster#7]
Would it be possible to add a usenet verifier process to this? A process that on a time interval after the files were uploaded were verified to a minimum completeness on usenet. And/or  from a watch folder, drop an nzb in the watch folder and verify the completeness. Then if completeness greater than desired, delete the backup files else repost.

I understand the purpose of this app and if this in not within its scope, I understand.

Thank you for your time and this app.

**Comment by boranblok** [comment]
Well, currently the verification step is just verifying if the post appeared on a usenet index. Almost any newznab compatible indexer can be checked if the post is indexed.

I have never had a file download not work. So the only thing that could happen is DMCA takedowns,

For this a verification download is not useful anyways, because a valid download at 60 minutes after upload might no longer be valid 61 minutes after upload.

**Comment by jonnyboy** [comment]
Ok, I will look at doing an indexer.

Thanks

**Comment by boranblok** [comment]
Johhny, just a bit of a question to you, what is your big picture. What exactly is your goal with the uploads?

**Comment by jonnyboy** [comment]
I am using this as a private backup for my site. Everything is obfuscated and passworded. I would like to upload the files and verify the nzb, then delete my backups. In intervals I would like to check the completeness of the nzb, so I can upload again if needed.

Another thought was is to upload a par2 set separately so that even with DMCA takedowns I can maintain the integrity of the uploads.

I have another process, that when someone on the site requests the file, it will download the nzb and make the file available to the user.

I guess you could call this an automated reseed process. It works well, but the uploader I am currently using fails 20-30% of the time, more often on the large files. I am hoping to replace that uploader with this.

**Comment by boranblok** [comment]
Yeah, I am sorry to say that that is a bit out of scope, there is no download process at all in the code even (the nntp client is stripped of all download logic to keep it simple)

But, you could always use an external process for this. The uploader outputs nzbs, if you have this input into the watchfolder of sabnzbd or another downloader with an nzb watchfolder you could then use a file duplicate detector to find what files were uploaded successfully to usenet and then delete the originals + the verification download.

However, be warned that even with offsite par2's usenet is not a reliable backup location.

**Comment by jonnyboy** [comment]
I already have a complete process, this app is just replacing the uploader.

**Comment by boranblok** [comment]
Hmmh, one thing I'd have to add I think is the ability to disable the verification process alltogether. Right now if it cannot find uploads on the index it will reupload.

However, if you just need a raw uploader and not all the surrounding logic of watch folders and verification you can always use the nntpPoster.exe this is the core uploading logic. This executable takes in a file and uploads it to usenet. I see it does not handle folders yet. I will modify this to take in both of these parameters since this is a bit of an oversight now.

**Comment by jonnyboy** [comment]
Very nice, thanks

**Comment by jonnyboy** [comment]
running command like this:

mono nntpPoster.exe backup/Default/87653322/sample.mp4

The process does not close, seems to be waiting for something. If I press enter, it closes.

**Comment by boranblok** [comment]
Yeah, that was some debug logic left in place.

I just released version 0.6.4 that fixes this, and adds folder support as well.

See the release page concerning what settings are relevant and which are not. I think for your process with all the rest in place using this simpeler "raw" usenet poster is a better fit.

**Comment by jonnyboy** [comment]
Thank you. Will try it now.
